name: Deploy to EasyDeploy
on:
  workflow_dispatch:
  push:
    paths:
      - 'easydeploy.yaml'
jobs:
  deploy:
    uses: hiyainc-labs/easydeploy/.github/workflows/deploy.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
      token: ${{ github.token }}
    secrets:
      EASYDEPLOY_CHECKOUT_TOKEN: ${{ secrets.EASYDEPLOY_CHECKOUT_TOKEN }}